import argparse
from _typeshed import Incomplete

def success(result): ...
def handle_exception(e, code=None, params=None): ...

class XenAPIException(Exception):
    code: Incomplete
    params: Incomplete
    def __init__(self, code, params): ...

class MissingDependency(Exception):
    missing: Incomplete
    def __init__(self, missing): ...
    def __str__(self) -> str: ...

class Rpc_light_failure(Exception):
    name: Incomplete
    args: Incomplete
    def __init__(self, name, args): ...
    def failure(self): ...

class Unimplemented(Rpc_light_failure):
    def __init__(self, name): ...

class InternalError(Rpc_light_failure):
    def __init__(self, error): ...

class UnmarshalException(InternalError):
    def __init__(self, thing, ty, desc): ...

class TypeError(InternalError):
    def __init__(self, expected, actual): ...

class UnknownMethod(InternalError):
    def __init__(self, name): ...

def is_long(x): ...

class ListAction(argparse.Action):
    def __call__(self, parser, namespace, values, option_string=None): ...
