from _typeshed import Incomplete

class LinstorError(Exception):
    _msg: Incomplete
    _errors: Incomplete
    def __init__(self, msg, all_errors=None) -> None: ...
    def all_errors(self): ...
    @property
    def message(self): ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...

class LinstorNetworkError(LinstorError):
    def __init__(self, msg, more_errors=None) -> None: ...

class LinstorTimeoutError(LinstorError):
    def __init__(self, msg, more_errors=None) -> None: ...

class LinstorApiCallError(LinstorError):
    _main_error: Incomplete
    def __init__(self, apicallresponse, all_errors=None) -> None: ...
    @property
    def main_error(self): ...

class LinstorArgumentError(LinstorError):
    def __init__(self, msg, more_errors=None) -> None: ...

class LinstorReadOnlyAfterSetError(LinstorError):
    def __init__(self, msg=None, more_errors=None) -> None: ...
