from _typeshed import Incomplete
from collections.abc import Generator
from linstor.resource import _Client as _Client

unicode = str

class KV(dict):
    _name: Incomplete
    _cached: Incomplete
    client: Incomplete
    _existing_client: Incomplete
    _rw_to_linstor: Incomplete
    def __init__(self, name, namespace: str = '/', cached: bool = True, uri: str = 'linstor://localhost', rw_to_linstor: bool = True, existing_client=None) -> None: ...
    def _get_connection(self): ...
    def _set_linstor_kv(self, k, v) -> None: ...
    def _del_linstor_kv(self, k, is_list_like: bool = False) -> None: ...
    @classmethod
    def _valid_string(cls, s): ...
    @classmethod
    def _normalize_ns(cls, ns): ...
    def _import(self) -> None: ...
    _ns: Incomplete
    def _set_ns(self, ns) -> None: ...
    def _key_ns_add(self, k): ...
    def _key_ns_del(self, k): ...
    @property
    def namespace(self): ...
    @namespace.setter
    def namespace(self, ns) -> None: ...
    def __delitem__(self, k) -> None: ...
    def __setitem__(self, k, v) -> None: ...
    def __getitem__(self, k): ...
    def __contains__(self, k) -> bool: ...
    def __iter__(self): ...
    def clear(self) -> None: ...
    def get(self, k, d=None): ...
    def items(self) -> Generator[Incomplete]: ...
    def keys(self): ...
    def pop(self, *args): ...
    def popitem(self): ...
    def setdefault(self, k, d=None): ...
    def update(self, *args, **kwargs) -> None: ...
    def values(self) -> Generator[Incomplete]: ...
