import types
from _typeshed import Incomplete
from enum import Enum
from http.client import HTTPConnection
from linstor import responses as responses
from linstor.errors import LinstorApiCallError as LinstorApiCallError, LinstorArgumentError as LinstorArgumentError, LinstorError as LinstorError, LinstorNetworkError as LinstorNetworkError, LinstorTimeoutError as LinstorTimeoutError
from linstor.responses import ApiCallResponse as ApiCallResponse, BackupInfoResponse as BackupInfoResponse, BackupListResponse as BackupListResponse, BackupQueues as BackupQueues, CloneStarted as CloneStarted, CloneStatus as CloneStatus, ControllerProperties as ControllerProperties, ControllerVersion as ControllerVersion, ErrorReport as ErrorReport, FileResponse as FileResponse, KeyValueStoresResponse as KeyValueStoresResponse, MaxVolumeSizeResponse as MaxVolumeSizeResponse, NodeConnection as NodeConnection, NodeConnectionsResponse as NodeConnectionsResponse, NodeListResponse as NodeListResponse, PhysicalStorageList as PhysicalStorageList, QuerySizeInfoResponse as QuerySizeInfoResponse, RemoteListResponse as RemoteListResponse, ResourceConnection as ResourceConnection, ResourceConnectionsResponse as ResourceConnectionsResponse, ResourceDefinitionResponse as ResourceDefinitionResponse, ResourceGroupResponse as ResourceGroupResponse, ResourceResponse as ResourceResponse, SnapshotResponse as SnapshotResponse, SpaceReport as SpaceReport, StoragePoolDefinitionResponse as StoragePoolDefinitionResponse, StoragePoolDriver as StoragePoolDriver, StoragePoolListResponse as StoragePoolListResponse, SyncStatus as SyncStatus, VolumeDefinitionResponse as VolumeDefinitionResponse, VolumeGroupResponse as VolumeGroupResponse, VolumeResponse as VolumeResponse
from linstor.size_calc import SizeCalc as SizeCalc
from linstor.version import VERSION as VERSION

API_VERSION_MIN: str
API_VERSION = API_VERSION_MIN

def _pquote(pathfmt, *args, **kwargs): ...

class ResourceData:
    _node_name: Incomplete
    _rsc_name: Incomplete
    _diskless: Incomplete
    _storage_pool: Incomplete
    _node_id: Incomplete
    _layer_list: Incomplete
    _drbd_diskless: Incomplete
    _nvme_initiator: Incomplete
    _ebs_initiator: Incomplete
    _active: Incomplete
    _drbd_tcp_ports: Incomplete
    def __init__(self, node_name, rsc_name, diskless: bool = False, storage_pool=None, node_id=None, layer_list=None, drbd_diskless: bool = False, nvme_initiator: bool = False, ebs_initiator: bool = False, active: bool = True, drbd_tcp_ports=None) -> None: ...
    @property
    def node_name(self): ...
    @property
    def rsc_name(self): ...
    @property
    def diskless(self): ...
    @property
    def storage_pool(self): ...
    @property
    def node_id(self): ...
    @property
    def layer_list(self): ...
    @property
    def drbd_diskless(self): ...
    @property
    def nvme_initiator(self): ...
    @property
    def ebs_initiator(self): ...
    @property
    def active(self): ...
    @property
    def drbd_tcp_ports(self): ...

class LogLevelEnum(Enum):
    ERROR = 'ERROR'
    WARN = 'WARN'
    INFO = 'INFO'
    DEBUG = 'DEBUG'
    TRACE = 'TRACE'
    def __str__(self) -> str: ...
    @staticmethod
    def check(value): ...

class Linstor:
    _node_types: Incomplete
    API_SINGLE_NODE_REQ: str
    API_SCHEDULE_BY_RESOURCE_LIST: str
    API_SCHEDULE_BY_RESOURCE_LIST_DETAILS: str
    API_SINGLE_NODE_CONN_REQ: str
    APICALL2RESPONSE: Incomplete
    REST_PORT: int
    REST_HTTPS_PORT: int
    _ctrl_host: Incomplete
    _timeout: Incomplete
    _keep_alive: Incomplete
    _rest_conn: Optional[HTTPConnection]
    _connected: bool
    _mode_curl: bool
    _ctrl_version: Incomplete
    _username: Incomplete
    _password: Incomplete
    _certfile: Incomplete
    _keyfile: Incomplete
    _cafile: Incomplete
    _allow_insecure: bool
    _times_entered: int
    _http_headers: Incomplete
    def __init__(self, ctrl_host, timeout: int = 300, keep_alive: bool = False, agent_info: str = '') -> None: ...
    def __del__(self) -> None: ...
    def __enter__(self): ...
    def __exit__(self, type: type[BaseException] | None, value: BaseException | None, traceback: types.TracebackType | None) -> None: ...
    @property
    def username(self): ...
    @username.setter
    def username(self, username) -> None: ...
    @property
    def password(self): ...
    @password.setter
    def password(self, password) -> None: ...
    @property
    def certfile(self): ...
    @certfile.setter
    def certfile(self, certfile) -> None: ...
    @property
    def keyfile(self): ...
    @keyfile.setter
    def keyfile(self, keyfile) -> None: ...
    @property
    def cafile(self): ...
    @cafile.setter
    def cafile(self, cafile) -> None: ...
    @property
    def allow_insecure(self): ...
    @allow_insecure.setter
    def allow_insecure(self, val) -> None: ...
    def __output_curl_command(self, method, path, body) -> None: ...
    @classmethod
    def _current_milli_time(cls): ...
    @classmethod
    def parse_volume_size_to_kib(cls, size_str): ...
    @classmethod
    def _decode_response_data(cls, response): ...
    def _require_version(self, required_version, msg: str = 'REST action not supported by server') -> None: ...
    def api_version_smaller(self, version): ...
    def _rest_request_base(self, apicall, method, path, body=None, reconnect: bool = True): ...
    def _handle_response_error(self, response, method, path, raise_error: bool = False): ...
    def _rest_request(self, apicall, method, path, body=None, reconnect: bool = True, raise_error: bool = False): ...
    def _rest_request_raw(self, apicall, method, path, body=None, reconnect: bool = True): ...
    def _rest_request_download(self, apicall, method, path, body=None, reconnect: bool = True, to_file=None): ...
    def __convert_rest_response(self, apicall, response, path): ...
    @property
    def curl(self): ...
    @curl.setter
    def curl(self, enable) -> None: ...
    @classmethod
    def all_api_responses_no_error(cls, replies): ...
    @classmethod
    def all_api_responses_success(cls, replies): ...
    @classmethod
    def filter_api_call_response(cls, replies): ...
    @classmethod
    def filter_api_call_response_errors(cls, replies): ...
    @classmethod
    def return_if_failure(cls, replies_): ...
    @classmethod
    def return_if_error(cls, replies_): ...
    @classmethod
    def _modify_props(cls, msg, property_dict, delete_props=None): ...
    @classmethod
    def has_linstor_https(cls, hostname, port): ...
    def connect(self): ...
    @property
    def connected(self): ...
    @property
    def is_secure_connection(self): ...
    def disconnect(self) -> None: ...
    def _require_node_is_active(self, net_interface, value: bool = True) -> None: ...
    def node_create(self, node_name, node_type, ip, com_type=..., port=None, netif_name: str = 'default', property_dict=None): ...
    def node_create_ebs(self, node_name, ebs_remote_name): ...
    def node_modify(self, node_name, node_type=None, property_dict=None, delete_props=None): ...
    def node_delete(self, node_name, async_msg: bool = False): ...
    def node_lost(self, node_name, async_msg: bool = False): ...
    def node_reconnect(self, node_names): ...
    def node_restore(self, node_name, delete_resources=None, delete_snapshots=None): ...
    def node_evacuate(self, node_name, target=None, do_not_target=None): ...
    def netinterface_create(self, node_name, interface_name, ip, port=None, com_type=None, is_active: bool = False): ...
    def netinterface_modify(self, node_name, interface_name, ip=None, port=None, com_type=None, is_active: bool = False): ...
    def netinterface_delete(self, node_name, interface_name): ...
    def net_interface_list(self, node_name): ...
    def node_list(self, filter_by_nodes=None, filter_by_props=None): ...
    def node_list_raise(self, filter_by_nodes=None, filter_by_props=None): ...
    def node_types(self): ...
    def storage_pool_dfn_create(self, name): ...
    def storage_pool_dfn_modify(self, name, property_dict, delete_props=None): ...
    def storage_pool_dfn_delete(self, name): ...
    def storage_pool_dfn_list(self): ...
    def storage_pool_dfn_max_vlm_sizes(self, place_count, storage_pool_name=None, do_not_place_with=None, do_not_place_with_regex=None, replicas_on_same=None, replicas_on_different=None, x_replicas_on_different=None): ...
    @staticmethod
    def _filter_props(props, namespace: str = ''): ...
    def storage_pool_create(self, node_name, storage_pool_name, storage_driver, driver_pool_name, shared_space=None, property_dict=None, external_locking: bool = False): ...
    def storage_pool_modify(self, node_name, storage_pool_name, property_dict, delete_props=None): ...
    def storage_pool_delete(self, node_name, storage_pool_name): ...
    def storage_pool_list(self, filter_by_nodes=None, filter_by_stor_pools=None, filter_by_props=None): ...
    def storage_pool_list_raise(self, filter_by_nodes=None, filter_by_stor_pools=None, filter_by_props=None): ...
    @classmethod
    def layer_list(cls): ...
    @classmethod
    def provider_list(cls): ...
    def resource_group_create(self, name, description=None, place_count=None, storage_pool=None, do_not_place_with=None, do_not_place_with_regex=None, replicas_on_same=None, replicas_on_different=None, x_replicas_on_different=None, diskless_on_remaining=None, layer_list=None, provider_list=None, property_dict=None, diskless_storage_pool=None, peer_slots=None): ...
    def resource_group_modify(self, name, description=None, place_count=None, storage_pool=None, do_not_place_with=None, do_not_place_with_regex=None, replicas_on_same=None, replicas_on_different=None, x_replicas_on_different=None, diskless_on_remaining=None, layer_list=None, provider_list=None, property_dict=None, delete_props=None, diskless_storage_pool=None, peer_slots=None): ...
    def resource_group_delete(self, name): ...
    def resource_group_list_raise(self, filter_by_resource_groups=None, filter_by_props=None): ...
    def resource_group_spawn(self, rsc_grp_name, rsc_dfn_name, vlm_sizes, partial: bool = False, definitions_only: bool = False, external_name=None, place_count=None, storage_pool=None, do_not_place_with=None, do_not_place_with_regex=None, replicas_on_same=None, replicas_on_different=None, x_replicas_on_different=None, diskless_on_remaining=None, layer_list=None, provider_list=None, diskless_storage_pool=None, peer_slots=None, volume_passphrases=None): ...
    def resource_group_qmvs(self, rsc_grp_name): ...
    def resource_group_query_size_info(self, rsc_grp_name, place_count=None, storage_pool=None, do_not_place_with=None, do_not_place_with_regex=None, replicas_on_same=None, replicas_on_different=None, x_replicas_on_different=None, diskless_on_remaining=None, layer_list=None, provider_list=None, diskless_storage_pool=None): ...
    def resource_group_adjust(self, rsc_grp_name): ...
    def volume_group_create(self, resource_grp_name, volume_nr=None, property_dict=None, gross: bool = False): ...
    def volume_group_modify(self, resource_grp_name, volume_nr, property_dict=None, delete_props=None, gross=None): ...
    def volume_group_delete(self, resource_grp_name, volume_nr): ...
    def volume_group_list_raise(self, resource_grp_name): ...
    def resource_dfn_create(self, name, port=None, external_name=None, layer_list=None, resource_group=None, peer_slots=None): ...
    def resource_dfn_clone(self, src_name, clone_name, clone_external_name=None, use_zfs_clone=None, volume_passphrases=None, layer_list=None, resource_group=None, property_dict=None, delete_props=None): ...
    def resource_dfn_clone_status(self, src_name, clone_name): ...
    def resource_dfn_clone_wait_complete(self, src_name, clone_name, wait_interval: float = 1.0, timeout=None): ...
    def resource_dfn_sync_status(self, rsc_name): ...
    def resource_dfn_wait_synced(self, rsc_name, wait_interval: float = 1.0, timeout=None): ...
    def resource_dfn_modify(self, name, property_dict, delete_props=None, peer_slots=None, resource_group=None, port=None): ...
    def resource_dfn_delete(self, name, async_msg: bool = False): ...
    def resource_dfn_list(self, query_volume_definitions: bool = True, filter_by_resource_definitions=None, filter_by_props=None): ...
    def resource_dfn_list_raise(self, query_volume_definitions: bool = True, filter_by_resource_definitions=None, filter_by_props=None): ...
    def resource_dfn_props_list(self, rsc_name, filter_by_namespace: str = ''): ...
    def volume_dfn_create(self, rsc_name, size, volume_nr=None, minor_nr=None, encrypt: bool = False, storage_pool=None, gross: bool = False, passphrase=None): ...
    def volume_dfn_modify(self, rsc_name, volume_nr, set_properties=None, delete_properties=None, size=None, gross=None): ...
    def volume_dfn_delete(self, rsc_name, volume_nr, async_msg: bool = False): ...
    def _volume_dfn_size(self, rsc_name, volume_nr): ...
    def volume_dfn_modify_passphrase(self, rsc_name, volume_nr, new_passphrase): ...
    def resource_create(self, rscs, async_msg: bool = False): ...
    def _set_select_filter_body(self, body, place_count, storage_pool, do_not_place_with, do_not_place_with_regex, replicas_on_same, replicas_on_different, x_replicas_on_different, diskless_on_remaining, layer_list, provider_list, additional_place_count, diskless_type, diskless_storage_pool): ...
    def resource_auto_place(self, rsc_name, place_count, storage_pool=None, do_not_place_with=None, do_not_place_with_regex=None, replicas_on_same=None, replicas_on_different=None, x_replicas_on_different=None, diskless_on_remaining: bool = False, async_msg: bool = False, layer_list=None, provider_list=None, additional_place_count=None, diskless_type=None, diskless_storage_pool=None): ...
    def resource_create_and_auto_place(self, rsc_name, size, place_count, storage_pool=None, diskless_on_remaining: bool = False): ...
    def resource_make_available(self, node_name, rsc_name, diskful: bool = False, layer_list=None, drbd_tcp_ports=None): ...
    def resource_modify(self, node_name, rsc_name, property_dict, delete_props=None): ...
    def resource_delete(self, node_name, rsc_name, async_msg: bool = False, keep_tiebreaker: bool = False): ...
    def resource_delete_if_diskless(self, node_name, rsc_name): ...
    def resource_activate(self, node_name, rsc_name): ...
    def resource_deactivate(self, node_name, rsc_name): ...
    def resource_list(self, filter_by_nodes=None, filter_by_resources=None, filter_by_props=None): ...
    def resource_list_raise(self, filter_by_nodes=None, filter_by_resources=None, filter_by_props=None): ...
    def volume_list(self, filter_by_nodes=None, filter_by_stor_pools=None, filter_by_resources=None, filter_by_props=None): ...
    def volume_list_raise(self, filter_by_nodes=None, filter_by_stor_pools=None, filter_by_resources=None, filter_by_props=None): ...
    def volume_modify(self, node_name, rsc_name, vlm_nr, property_dict, delete_props=None): ...
    def resource_toggle_disk(self, node_name, rsc_name, storage_pool=None, diskless: bool = False, async_msg: bool = False, migrate_from=None): ...
    def controller_props(self): ...
    @classmethod
    def _split_prop_key(cls, fkey): ...
    def controller_set_prop(self, key, value): ...
    def controller_del_prop(self, key): ...
    def controller_backupdb(self, backup_name): ...
    def controller_info(self): ...
    def controller_version(self): ...
    def controller_host(self): ...
    def controller_set_log_level(self, level, glob: bool = False, library: bool = False): ...
    def crypt_create_passphrase(self, passphrase): ...
    def crypt_enter_passphrase(self, passphrase): ...
    def crypt_modify_passphrase(self, old_passphrase, new_passphrase): ...
    def resource_conn_modify(self, rsc_name, node_a, node_b, property_dict, delete_props): ...
    def resource_conn_list(self, rsc_name): ...
    def resource_conn_list_raise(self, rsc_name): ...
    def resource_conn_node_list_raise(self, rsc_name, node_a, node_b): ...
    def node_conn_modify(self, node_a, node_b, property_dict, delete_props): ...
    def node_conn_list_specific_pair(self, node_a, node_b): ...
    def node_conn_list(self, node_a=None, node_b=None): ...
    def _node_conn_list(self, api_call, node_a=None, node_b=None): ...
    def node_conn_list_raise(self, node_a=None, node_b=None): ...
    def node_set_log_level(self, node_name, level, library: bool = False): ...
    def drbd_proxy_enable(self, rsc_name, node_a, node_b, port=None): ...
    def drbd_proxy_disable(self, rsc_name, node_a, node_b): ...
    def drbd_proxy_modify(self, rsc_name, property_dict=None, delete_props=None, compression_type=None, compression_property_dict=None): ...
    def snapshot_create(self, node_names, rsc_name, snapshot_name, async_msg: bool = False): ...
    def snapshot_create_multi(self, node_names, rsc_names, snapshot_name): ...
    def snapshot_volume_definition_restore(self, from_resource, from_snapshot, to_resource): ...
    def snapshot_resource_restore(self, node_names, from_resource, from_snapshot, to_resource, storpool_rename_map=None): ...
    def snapshot_delete(self, rsc_name, snapshot_name, node_names=None): ...
    def snapshot_rollback(self, rsc_name, snapshot_name, zfs_rollback_strategy=None): ...
    def snapshot_dfn_list(self, filter_by_nodes=None, filter_by_resources=None): ...
    def snapshot_dfn_list_raise(self, filter_by_nodes=None, filter_by_resources=None): ...
    def snapshot_dfn_modify(self, resource_name, snapshot_name, property_dict, delete_props=None): ...
    def error_report_list(self, nodes=None, with_content: bool = False, since=None, to=None, ids=None): ...
    def error_report_delete(self, nodes=None, since=None, to=None, exception=None, version=None, ids=None): ...
    def keyvaluestore_modify(self, instance_name, property_dict=None, delete_props=None): ...
    def keyvaluestores(self): ...
    def keyvaluestore_list(self, instance_name): ...
    def physical_storage_list(self): ...
    def physical_storage_create_device_pool(self, node_name, provider_kind, device_paths, pool_name=None, raid_level: str = 'JBOD', vdo_enable: bool = False, vdo_logical_size_kib=None, vdo_slab_size_kib=None, storage_pool_name=None, storage_pool_props=None, sed: bool = False, pv_create_arguments=None, vg_create_arguments=None, lv_create_arguments=None, zpool_create_arguments=None): ...
    def sos_report_create(self, since=None, nodes=None, rscs=None, exclude=None, include_ctrl: bool = True): ...
    def sos_report_download(self, since=None, to_file=None, nodes=None, rscs=None, exclude=None, include_ctrl: bool = True): ...
    def space_reporting_query(self): ...
    def backup_list(self, remote_name, resource_name=None, snap_name=None): ...
    def backup_create(self, remote_name, resource_name, incremental: bool = True, node_name=None, snap_name=None): ...
    def backup_delete(self, remote_name, bak_id=None, bak_id_prefix=None, cascade: bool = False, timestamp=None, resource_name=None, node_name=None, all_linstor: bool = False, all_local_cluster: bool = False, s3_key=None, dryrun=None, keep_snaps=None): ...
    def backup_restore(self, remote_name, target_node_name, target_resource_name, resource_name=None, bak_id=None, passphrase=None, stor_pool_map=None, download_only: bool = False, force_restore: bool = False, snap_name=None, dst_rsc_grp=None, force_mv_rsc_grp: bool = False): ...
    def backup_abort(self, remote_name, resource_name, restore=None, create=None, snapshot=None): ...
    def backup_ship(self, remote_name, src_rsc_name, dst_rsc_name, src_node=None, dst_node=None, dst_net_if=None, dst_stor_pool=None, stor_pool_rename=None, download_only: bool = False, force_restore: bool = False, dst_rsc_grp=None, force_mv_rsc_grp: bool = False, force_full=None, src_snap=None): ...
    def backup_info(self, remote_name, resource_name=None, bak_id=None, target_node=None, stor_pool_map=None, snap_name=None): ...
    def backup_schedule_enable(self, remote_name, schedule_name, resource_name=None, resource_group_name=None, preferred_node=None, dst_stor_pool=None, storpool_rename_map=None, force_restore: bool = False, dst_rsc_grp=None, force_mv_rsc_grp: bool = False, dst_rsc_name=None): ...
    def backup_schedule_disable(self, remote_name, schedule_name, resource_name=None, resource_group_name=None): ...
    def backup_schedule_delete(self, remote_name, schedule_name, resource_name=None, resource_group_name=None): ...
    def backup_queue_list(self, nodes=None, snaps=None, rscs=None, remotes=None, snap_to_node: bool = False): ...
    def remote_list(self): ...
    def remote_create_s3(self, remote_name, endpoint, region, bucket, access_key, secret_key, use_path_style: bool = False): ...
    def remote_modify_s3(self, remote_name, endpoint=None, region=None, bucket=None, access_key=None, secret_key=None): ...
    def remote_create_linstor(self, remote_name, url, passphrase=None, cluster_id=None): ...
    def remote_modify_linstor(self, remote_name, url=None, passphrase=None, cluster_id=None): ...
    def remote_create_ebs(self, remote_name, availability_zone, access_key, secret_key, endpoint=None, region=None): ...
    def remote_modify_ebs(self, remote_name, endpoint=None, region=None, availability_zone=None, access_key=None, secret_key=None): ...
    def remote_delete(self, remote_name): ...
    def stats(self): ...
    def file_list(self): ...
    def file_show(self, file_name): ...
    def file_modify(self, file_name, new_content): ...
    def file_delete(self, file_name): ...
    def file_deploy(self, file_name, rsc_name): ...
    def file_undeploy(self, file_name, rsc_name): ...
    def schedule_list(self): ...
    def schedule_list_by_resource(self, filter_by_resource=None, filter_by_remote=None, filter_by_schedule=None, active_only: bool = False): ...
    def schedule_list_by_resource_details(self, resource_name): ...
    def schedule_create(self, schedule_name, full_cron, keep_local=None, keep_remote=None, on_failure=None, incremental_cron=None, max_retries=None): ...
    def schedule_modify(self, schedule_name, full_cron=None, keep_local=None, keep_remote=None, on_failure=None, incremental_cron=None, max_retries=None): ...
    def schedule_delete(self, schedule_name): ...

class MultiLinstor(Linstor):
    _ctrl_host_list: list[str]
    def __init__(self, ctrl_host_list, timeout: int = 300, keep_alive: bool = False, agent_info: str = '') -> None: ...
    _ctrl_host: Incomplete
    def connect(self): ...
    @classmethod
    def controller_uri_list(cls, controller_list): ...
