import linstor
from _typeshed import Incomplete
from linstor.linstorapi import Linstor as Linstor
from linstor.responses import ApiCallResponse as ApiCallResponse
from linstor.sharedconsts import FLAG_DISKLESS as FLAG_DISKLESS

PYTHON2: bool
unicode = str

class _Utils:
    @classmethod
    def to_unicode(cls, t): ...

class _Client:
    _uri_list: list[str]
    timeout: Incomplete
    keep_alive: Incomplete
    agent_info: Incomplete
    def __init__(self, uris, timeout: int = 300, keep_alive: bool = False, agent_info: str = '') -> None: ...
    @property
    def uri_list(self): ...
    @uri_list.setter
    def uri_list(self, uri_list) -> None: ...

class _Placement:
    redundancy: Incomplete
    storage_pool: Incomplete
    diskless_storage_pool: Incomplete
    diskless_on_remaining: bool
    def __init__(self, redundancy=None) -> None: ...

class Volume:
    _size: Incomplete
    _minor: Incomplete
    _device_path: str
    _storage_pool_name: str
    _volume_id: Incomplete
    _rsc_name: Incomplete
    _client_ref: Optional[linstor.Linstor]
    _assignments: Incomplete
    def __init__(self, size) -> None: ...
    def __repr__(self) -> str: ...
    @property
    def storage_pool_name(self): ...
    @property
    def device_path(self): ...
    @device_path.setter
    def device_path(self, device_path) -> None: ...
    @property
    def minor(self): ...
    @minor.setter
    def minor(self, minor) -> None: ...
    @property
    def size(self): ...
    @classmethod
    def _size_to_bytes(cls, size): ...
    @size.setter
    def size(self, size) -> None: ...
    def _delete(self) -> None: ...

class _VolumeDict(dict):
    def __init__(self) -> None: ...
    def __setitem__(self, k, v) -> None: ...
    def __delitem__(self, k) -> None: ...

class Resource:
    _lin: Incomplete
    def _update_volumes(f): ...
    _name: Incomplete
    _port: Incomplete
    _resource_group_name: Optional[str]
    client: Incomplete
    placement: Incomplete
    volumes: dict[int, Volume]
    defined: bool
    _allow_two_primaries: bool
    _assignments: Incomplete
    _linstor_name: Incomplete
    _existing_client: Incomplete
    def __init__(self, name, uri: str = 'linstor://localhost', existing_client=None, resource_group=None) -> None: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    @classmethod
    def from_resource_group(cls, uri, resource_group_name, resource_name, vlm_sizes, timeout: int = 300, keep_alive: bool = False, definitions_only: bool = False, existing_client=None, agent_info: str = ''): ...
    def _get_connection(self): ...
    def _set_properties(self) -> None: ...
    def _maybe_create_rd_and_vd(self) -> None: ...
    def _create_volume_definitions(self) -> None: ...
    def __update_volumes(self): ...
    @property
    def allow_two_primaries(self): ...
    @allow_two_primaries.setter
    def allow_two_primaries(self, value) -> None: ...
    @property
    def name(self): ...
    @name.setter
    def name(self, name) -> None: ...
    @property
    def linstor_name(self): ...
    @linstor_name.setter
    def linstor_name(self, name) -> None: ...
    @property
    def port(self): ...
    @port.setter
    def port(self, port_nr) -> None: ...
    @property
    def resource_group_name(self): ...
    @_update_volumes
    def autoplace(self): ...
    @_update_volumes
    def activate(self, node_name, diskful: bool = False): ...
    def deactivate(self, node_name): ...
    @_update_volumes
    def _create_or_toggle(self, node_name, diskless): ...
    def snapshot_create(self, name): ...
    def snapshot_delete(self, name): ...
    def snapshot_rollback(self, name): ...
    def restore_from_snapshot(self, snapshot_name, resource_name_to): ...
    def clone(self, clone_name, clone_external_name=None, timeout=None, use_zfs_clone=None, volume_passphrases=None, layer_list=None, resource_group=None, property_dict=None, delete_props=None): ...
    def diskless(self, node_name): ...
    def diskful(self, node_name): ...
    def is_diskless(self, node_name): ...
    def is_diskful(self, node_name): ...
    def is_assigned(self, node_name): ...
    def diskless_nodes(self): ...
    def diskful_nodes(self): ...
    def is_thin(self): ...
    _volumes: Incomplete
    def _delete(self, node_name=None): ...
    def delete(self, node_name=None, snapshots: bool = True): ...
    def drbd_proxy_enable(self, node_name_a, node_name_b): ...
    def drbd_proxy_disable(self, node_name_a, node_name_b): ...
