from _typeshed import Incomplete
from linstor.resource import Resource as Resource, _Client as _Client

class ResourceGroup:
    _name: Incomplete
    _uri: Incomplete
    client: Incomplete
    _existing_client: Incomplete
    _description: Incomplete
    _redundancy: Incomplete
    _storage_pool_list: Incomplete
    _do_not_place_with: Incomplete
    _do_not_place_with_regex: Incomplete
    _replicas_on_same: Incomplete
    _replicas_on_different: Incomplete
    _x_replicas_on_different: Incomplete
    _diskless_on_remaining: Incomplete
    _layer_list: Incomplete
    _provider_list: Incomplete
    _property_dict: Incomplete
    _nr_volumes: int
    _nr_volumes_default: int
    def __init__(self, name, uri: str = 'linstor://localhost', existing_client=None, agent_info: str = '') -> None: ...
    def _get_connection(self): ...
    @property
    def name(self): ...
    @name.setter
    def name(self, name) -> None: ...
    @property
    def description(self): ...
    @description.setter
    def description(self, description): ...
    @property
    def redundancy(self): ...
    @redundancy.setter
    def redundancy(self, redundancy): ...
    @property
    def storage_pool(self): ...
    @storage_pool.setter
    def storage_pool(self, storage_pool): ...
    @property
    def do_not_place_with(self): ...
    @do_not_place_with.setter
    def do_not_place_with(self, do_not_place_with): ...
    @property
    def do_not_place_with_regex(self): ...
    @do_not_place_with_regex.setter
    def do_not_place_with_regex(self, do_not_place_with_regex): ...
    @property
    def replicas_on_same(self): ...
    @replicas_on_same.setter
    def replicas_on_same(self, replicas_on_same): ...
    @property
    def replicas_on_different(self): ...
    @property
    def x_replicas_on_different(self): ...
    @replicas_on_different.setter
    def replicas_on_different(self, replicas_on_different): ...
    @x_replicas_on_different.setter
    def x_replicas_on_different(self, x_replicas_on_different): ...
    @property
    def diskless_on_remaining(self): ...
    @diskless_on_remaining.setter
    def diskless_on_remaining(self, diskless_on_remaining): ...
    def _set_nr_volumes(self, nr_volumes): ...
    @property
    def nr_volumes(self): ...
    @nr_volumes.setter
    def nr_volumes(self, nr_volumes): ...
    @property
    def layer_list(self): ...
    @layer_list.setter
    def layer_list(self, layer_list): ...
    @property
    def provider_list(self): ...
    @provider_list.setter
    def provider_list(self, provider_list): ...
    @property
    def property_dict(self): ...
    @property_dict.setter
    def property_dict(self, property_dict): ...
    def delete(self): ...
    def create_resource(self, resource_name, vlm_sizes): ...
    def query_max_volume_size(self): ...
    def _modify_or_create(self, what: str = 'modify'): ...
    def _update(self): ...
    def _update_or_create(self): ...
