from .errors import LinstorError as LinstorError
from _typeshed import Incomplete

class RESTMessageResponse:
    _rest_data: Incomplete
    def __init__(self, rest_data) -> None: ...
    def data(self, version): ...
    @property
    def data_v0(self): ...
    @property
    def data_v1(self): ...
    @classmethod
    def _unix_epoch_field_value(cls, unix_epoch_val): ...
    def __nonzero__(self): ...
    def __bool__(self) -> bool: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...

class ApiCallResponse(RESTMessageResponse):
    def __init__(self, rest_data) -> None: ...
    @classmethod
    def from_json(cls, json_data): ...
    @classmethod
    def from_str(cls, message, code=None): ...
    def is_error(self, code=None): ...
    def is_warning(self): ...
    def is_info(self): ...
    def is_success(self): ...
    @property
    def ret_code(self): ...
    @property
    def message(self): ...
    @property
    def cause(self): ...
    @property
    def correction(self): ...
    @property
    def details(self): ...
    @property
    def object_refs(self): ...
    @property
    def error_report_ids(self): ...
    @property
    def data_v0(self): ...
    def __eq__(self, other): ...
    def __hash__(self): ...
    def __str__(self) -> str: ...

class ErrorReport(RESTMessageResponse):
    def __init__(self, data) -> None: ...
    @property
    def datetime(self): ...
    @property
    def id(self): ...
    @property
    def text(self): ...
    @property
    def node_name(self): ...
    @property
    def node_names(self): ...
    @property
    def module(self): ...
    @property
    def version(self): ...
    @property
    def peer(self): ...
    @property
    def exception(self): ...
    @property
    def exception_message(self): ...
    @property
    def origin_file(self): ...
    @property
    def origin_line(self): ...
    @property
    def data_v0(self): ...

class NodeType:
    CONTROLLER: Incomplete
    SATELLITE: Incomplete
    COMBINED: Incomplete
    AUXILIARY: Incomplete

class NetInterface(RESTMessageResponse):
    def __init__(self, rest_data) -> None: ...
    @property
    def name(self): ...
    @property
    def address(self): ...
    @property
    def stlt_port(self): ...
    @property
    def stlt_encryption_type(self): ...
    @property
    def is_active(self): ...
    @property
    def data_v0(self): ...

class Node(RESTMessageResponse):
    def __init__(self, rest_data) -> None: ...
    @property
    def name(self): ...
    @property
    def type(self): ...
    @property
    def connection_status(self): ...
    @property
    def net_interfaces(self): ...
    @property
    def storage_providers(self): ...
    @property
    def resource_layers(self): ...
    @property
    def unsupported_providers(self): ...
    @property
    def unsupported_layers(self): ...
    @property
    def props(self): ...
    @property
    def properties(self): ...
    @property
    def flags(self): ...
    @property
    def eviction_timestamp(self): ...
    @property
    def data_v0(self): ...
    def __str__(self) -> str: ...

class NodeListResponse(RESTMessageResponse):
    def __init__(self, rest_data) -> None: ...
    @property
    def nodes(self): ...
    def node(self, node_name): ...
    @property
    def data_v0(self): ...

class NodeConnection(RESTMessageResponse):
    def __init__(self, data) -> None: ...
    @property
    def node_a(self): ...
    @property
    def node_b(self): ...
    @property
    def flags(self): ...
    @property
    def properties(self): ...
    @property
    def data_v0(self): ...

class NodeConnectionsResponse(RESTMessageResponse):
    def __init__(self, data) -> None: ...
    @property
    def node_connections(self): ...
    @property
    def data_v0(self): ...

class FreeSpace(RESTMessageResponse):
    def __init__(self, rest_data) -> None: ...
    @property
    def free_capacity(self): ...
    @property
    def total_capacity(self): ...
    def __str__(self) -> str: ...
    @property
    def data_v0(self): ...

class StoragePoolDriver:
    LVM: str
    LVMThin: str
    ZFS: str
    ZFSThin: str
    Diskless: str
    FILE: str
    FILEThin: str
    SPDK: str
    REMOTE_SPDK: str
    STORAGE_SPACES: str
    STORAGE_SPACES_THIN: str
    EBS_TARGET: str
    EBS_INIT: str
    @staticmethod
    def list(): ...
    @classmethod
    def diskless_driver(cls): ...
    @staticmethod
    def storage_driver_pool_to_props(storage_driver, driver_pool_name): ...
    @classmethod
    def storage_props_to_driver_pool(cls, storage_driver, props): ...

class StoragePool(RESTMessageResponse):
    DRIVER_KIND_MAP: Incomplete
    def __init__(self, rest_data) -> None: ...
    @property
    def name(self): ...
    @property
    def uuid(self): ...
    @property
    def node_name(self): ...
    @property
    def driver(self): ...
    @property
    def provider_kind(self): ...
    @property
    def properties(self): ...
    @property
    def static_traits(self): ...
    @property
    def free_space(self): ...
    @property
    def free_space_mgr_name(self): ...
    def supports_snapshots(self): ...
    def is_thin(self): ...
    def is_fat(self): ...
    def is_diskless(self): ...
    @property
    def reports(self): ...
    @property
    def data_v0(self): ...

class StoragePoolListResponse(RESTMessageResponse):
    def __init__(self, rest_data) -> None: ...
    @property
    def storage_pools(self): ...
    @property
    def data_v0(self): ...

class KeyValueStoresResponse(RESTMessageResponse):
    def __init__(self, data) -> None: ...
    def instances(self): ...
    def instance(self, name): ...

class KeyValueStore:
    _instance_name: Incomplete
    _props: Incomplete
    def __init__(self, instance_name, props) -> None: ...
    @property
    def properties(self): ...
    def __str__(self) -> str: ...

class DrbdVolumeDefinitionData(RESTMessageResponse):
    def __init__(self, rest_data) -> None: ...
    @property
    def resource_name_suffix(self): ...
    @property
    def minor(self): ...
    @property
    def number(self): ...

class VolumeDefinition(RESTMessageResponse):
    def __init__(self, rest_data) -> None: ...
    @property
    def number(self): ...
    @property
    def uuid(self): ...
    @property
    def size(self): ...
    @property
    def flags(self): ...
    @property
    def properties(self): ...
    @property
    def drbd_data(self): ...
    @property
    def data_v0(self): ...

class VolumeDefinitionResponse(RESTMessageResponse):
    def __init__(self, rest_data) -> None: ...
    @property
    def volume_definitions(self): ...
    @property
    def rest_data(self): ...

class DrbdLayer(RESTMessageResponse):
    def __init__(self, rest_data) -> None: ...
    @property
    def port(self): ...
    @property
    def secret(self): ...
    @property
    def peer_slots(self): ...

class ResourceDfnLayerData(RESTMessageResponse):
    def __init__(self, data) -> None: ...
    @property
    def type(self): ...
    @property
    def drbd_resource(self): ...

class ResourceDefinition(RESTMessageResponse):
    def __init__(self, rest_data) -> None: ...
    @property
    def name(self): ...
    @property
    def uuid(self): ...
    @property
    def external_name(self): ...
    @property
    def flags(self): ...
    @property
    def properties(self): ...
    @property
    def layer_data(self): ...
    @property
    def drbd_data(self): ...
    @property
    def volume_definitions(self): ...
    @property
    def resource_group_name(self): ...

class ResourceDefinitionResponse(RESTMessageResponse):
    def __init__(self, rest_data) -> None: ...
    @property
    def resource_definitions(self): ...
    @property
    def data_v0(self): ...

class SelectFilter(RESTMessageResponse):
    def __init__(self, rest_data) -> None: ...
    @property
    def place_count(self): ...
    @property
    def diskless_on_remaining(self): ...
    @property
    def storage_pool(self): ...
    @property
    def storage_pool_list(self): ...
    @property
    def not_place_with_rsc(self): ...
    @property
    def not_place_with_rsc_regex(self): ...
    @property
    def replicas_on_same(self): ...
    @property
    def replicas_on_different(self): ...
    @property
    def x_replicas_on_different(self): ...
    @property
    def layer_stack(self): ...
    @property
    def provider_list(self): ...
    def __str__(self) -> str: ...

class ResourceGroup(RESTMessageResponse):
    def __init__(self, rest_data) -> None: ...
    @property
    def name(self): ...
    @property
    def description(self): ...
    @property
    def properties(self): ...
    @property
    def select_filter(self): ...

class ResourceGroupResponse(RESTMessageResponse):
    def __init__(self, rest_data) -> None: ...
    @property
    def resource_groups(self): ...

class VolumeGroup(RESTMessageResponse):
    def __init__(self, rest_data) -> None: ...
    @property
    def number(self): ...
    @property
    def properties(self): ...
    @property
    def flags(self): ...

class VolumeGroupResponse(RESTMessageResponse):
    def __init__(self, rest_data) -> None: ...
    @property
    def volume_groups(self): ...

class ReplicationState(RESTMessageResponse):
    def __init__(self, data) -> None: ...
    @property
    def replication_state(self): ...
    @property
    def done_percentage(self): ...

class VolumeState(RESTMessageResponse):
    def __init__(self, data) -> None: ...
    @property
    def number(self): ...
    @property
    def disk_state(self): ...
    @property
    def replication_states(self): ...
    @property
    def data_v0(self): ...

class ResourceState(RESTMessageResponse):
    def __init__(self, data) -> None: ...
    @property
    def name(self): ...
    @property
    def rsc_name(self): ...
    @property
    def node_name(self): ...
    @property
    def in_use(self): ...
    @property
    def volume_states(self): ...
    @property
    def data_v0(self): ...

class DrbdConnection(RESTMessageResponse):
    def __init__(self, rest_data) -> None: ...
    @property
    def connected(self): ...
    @property
    def message(self): ...

class DrbdResource(RESTMessageResponse):
    def __init__(self, data) -> None: ...
    @property
    def node_id(self): ...
    @property
    def peer_slots(self): ...
    @property
    def al_stripes(self): ...
    @property
    def al_size(self): ...
    @property
    def connections(self): ...
    @property
    def tcp_ports(self): ...

class ResourceLayerData(RESTMessageResponse):
    def __init__(self, data) -> None: ...
    @property
    def name_suffix(self): ...
    @property
    def children(self): ...
    @property
    def layer_stack(self): ...
    @property
    def type(self): ...
    @property
    def drbd_resource(self): ...

class VolumeLayerData(RESTMessageResponse):
    def __init__(self, data) -> None: ...
    @property
    def layer_type(self): ...

class DrbdVolumeDefinition(RESTMessageResponse):
    def __init__(self, data) -> None: ...
    @property
    def number(self): ...
    @property
    def minor(self): ...
    @property
    def resource_name_suffix(self): ...

class DrbdVolumeData(RESTMessageResponse):
    def __init__(self, data) -> None: ...
    @property
    def drbd_volume_definition(self): ...
    @property
    def device_path(self): ...
    @property
    def backing_device(self): ...
    @property
    def meta_disk(self): ...
    @property
    def allocated_size(self): ...
    @property
    def usable_size(self): ...

class StorageVolumeData(RESTMessageResponse):
    def __init__(self, data) -> None: ...

class LUKSVolumeData(RESTMessageResponse):
    def __init__(self, data) -> None: ...

class Volume(RESTMessageResponse):
    def __init__(self, data) -> None: ...
    @property
    def number(self): ...
    @property
    def uuid(self): ...
    @property
    def storage_pool_name(self): ...
    @property
    def storage_pool_driver_name(self): ...
    @property
    def device_path(self): ...
    @property
    def allocated_size(self): ...
    @property
    def usable_size(self): ...
    @property
    def flags(self): ...
    @property
    def properties(self): ...
    @property
    def layer_data(self): ...
    @property
    def drbd_data(self): ...
    @property
    def storage_data(self): ...
    @property
    def luks_data(self): ...
    @property
    def state(self): ...
    @property
    def reports(self): ...
    @property
    def data_v0(self): ...

class VolumeResponse(RESTMessageResponse):
    def __init__(self, rest_data) -> None: ...
    @property
    def volumes(self): ...

class Resource(RESTMessageResponse):
    def __init__(self, rest_data) -> None: ...
    @property
    def name(self): ...
    @property
    def uuid(self): ...
    @property
    def node_name(self): ...
    @property
    def volumes(self): ...
    @property
    def flags(self): ...
    @property
    def properties(self): ...
    @property
    def effective_properties(self): ...
    @property
    def layer_data(self): ...
    @property
    def create_datetime(self): ...
    @property
    def data_v0(self): ...

class ResourceResponse(RESTMessageResponse):
    def __init__(self, rest_data) -> None: ...
    @property
    def resources(self): ...
    @property
    def nodes(self): ...
    @property
    def resource_states(self): ...
    @property
    def data_v0(self): ...

class ResourceConnection(RESTMessageResponse):
    def __init__(self, data) -> None: ...
    @property
    def node_a(self): ...
    @property
    def node_b(self): ...
    @property
    def flags(self): ...
    @property
    def properties(self): ...
    @property
    def port(self): ...
    @property
    def data_v0(self): ...

class ResourceConnectionsResponse(RESTMessageResponse):
    def __init__(self, data) -> None: ...
    @property
    def resource_connections(self): ...
    @property
    def data_v0(self): ...

class SnapshotVolumeDefinition(RESTMessageResponse):
    def __init__(self, data) -> None: ...
    @property
    def number(self): ...
    @property
    def size(self): ...
    @property
    def data_v0(self): ...

class Snapshot(RESTMessageResponse):
    def __init__(self, data) -> None: ...
    @property
    def name(self): ...
    @property
    def node_name(self): ...
    @property
    def flags(self): ...
    @property
    def create_datetime(self): ...
    @property
    def uuid(self): ...
    @property
    def snapshot_volumes(self): ...

class SnapshotVolume(RESTMessageResponse):
    def __init__(self, data) -> None: ...
    @property
    def uuid(self): ...
    @property
    def vlm_nr(self): ...
    @property
    def state(self): ...
    @property
    def properties(self): ...

class SnapshotDefinition(RESTMessageResponse):
    def __init__(self, data) -> None: ...
    @property
    def name(self): ...
    @property
    def uuid(self): ...
    @property
    def snapshot_name(self): ...
    @property
    def resource_name(self): ...
    @property
    def rsc_name(self): ...
    @property
    def nodes(self): ...
    @property
    def flags(self): ...
    @property
    def properties(self): ...
    @property
    def snapshot_volume_definitions(self): ...
    @property
    def snapshots(self): ...
    @property
    def data_v0(self): ...

class SnapshotResponse(RESTMessageResponse):
    def __init__(self, data) -> None: ...
    @property
    def snapshots(self): ...
    @property
    def data_v0(self): ...

class ControllerProperties(RESTMessageResponse):
    def __init__(self, data) -> None: ...
    @property
    def properties(self): ...

class StoragePoolDefinition(RESTMessageResponse):
    def __init__(self, data) -> None: ...
    @property
    def name(self): ...
    @property
    def properties(self): ...
    @property
    def data_v0(self): ...

class StoragePoolDefinitionResponse(RESTMessageResponse):
    def __init__(self, data) -> None: ...
    @property
    def storage_pool_definitions(self): ...
    @property
    def data_v0(self): ...

class Candidate(RESTMessageResponse):
    def __init__(self, data) -> None: ...
    @property
    def max_volume_size(self): ...
    @property
    def storage_pool(self): ...
    @property
    def node_names(self): ...
    @property
    def all_thin(self): ...

class MaxVolumeSizeResponse(RESTMessageResponse):
    def __init__(self, data) -> None: ...
    @property
    def candidates(self): ...
    @property
    def default_max_oversubscription_ratio(self): ...

class ControllerVersion(RESTMessageResponse):
    def __init__(self, data) -> None: ...
    @property
    def version(self): ...
    @property
    def git_hash(self): ...
    @property
    def build_time(self): ...
    @property
    def rest_api_version(self): ...

class NodeStorageEntry(RESTMessageResponse):
    def __init__(self, data) -> None: ...
    @property
    def device(self): ...
    @property
    def model(self): ...
    @property
    def serial(self): ...
    @property
    def wwn(self): ...

class PhysicalDevice(RESTMessageResponse):
    def __init__(self, data) -> None: ...
    @property
    def size(self): ...
    @property
    def rotational(self): ...
    @property
    def nodes(self): ...

class PhysicalStorageList(RESTMessageResponse):
    def __init__(self, data) -> None: ...
    @property
    def physical_devices(self): ...

class SpaceReport(RESTMessageResponse):
    def __init__(self, data) -> None: ...
    @property
    def report(self): ...

class CloneStarted(RESTMessageResponse):
    def __init__(self, rest_data) -> None: ...
    @property
    def location(self): ...
    @property
    def source_name(self): ...
    @property
    def clone_name(self): ...
    @property
    def messages(self): ...

class CloneStatus(RESTMessageResponse):
    def __init__(self, rest_data) -> None: ...
    @property
    def status(self): ...

class SyncStatus(RESTMessageResponse):
    def __init__(self, rest_data) -> None: ...
    @property
    def synced_on_all(self): ...

class S3Remote(RESTMessageResponse):
    def __init__(self, rest_data) -> None: ...
    @property
    def remote_name(self): ...
    @property
    def endpoint(self): ...
    @property
    def bucket(self): ...
    @property
    def region(self): ...
    @property
    def access_key(self): ...
    @property
    def secret_key(self): ...

class LinstorRemote(RESTMessageResponse):
    def __init__(self, rest_data) -> None: ...
    @property
    def remote_name(self): ...
    @property
    def url(self): ...
    @property
    def passphrase(self): ...

class EbsRemote(RESTMessageResponse):
    def __init__(self, rest_data) -> None: ...
    @property
    def remote_name(self): ...
    @property
    def endpoint(self): ...
    @property
    def region(self): ...
    @property
    def availability_zone(self): ...

class RemoteListResponse(RESTMessageResponse):
    def __init__(self, rest_data) -> None: ...
    @property
    def s3_remotes(self): ...
    @property
    def linstor_remotes(self): ...
    @property
    def ebs_remotes(self): ...

class Backup(RESTMessageResponse):
    def __init__(self, rest_data) -> None: ...
    @property
    def id(self): ...
    @property
    def start_time(self): ...
    @property
    def start_timestamp(self): ...
    @property
    def finished_time(self): ...
    @property
    def finished_timestamp(self): ...
    @property
    def origin_rsc_name(self): ...
    @property
    def origin_snap_name(self): ...
    @property
    def based_on(self): ...
    @property
    def success(self): ...
    @property
    def shipping(self): ...
    @property
    def restorable(self): ...

class BackupOther(RESTMessageResponse):
    def __init__(self, rest_data) -> None: ...
    @property
    def files(self): ...

class BackupListResponse(RESTMessageResponse):
    def __init__(self, rest_data) -> None: ...
    @property
    def linstor(self): ...
    @property
    def other(self): ...

class BackupInfoResponse(RESTMessageResponse):
    def __init__(self, rest_data) -> None: ...
    @property
    def rsc(self): ...
    @property
    def full(self): ...
    @property
    def snap(self): ...
    @property
    def latest(self): ...
    @property
    def count(self): ...
    @property
    def dl_size(self): ...
    @property
    def alloc_size(self): ...
    @property
    def storpools(self): ...

class BackupInfoStorPool(RESTMessageResponse):
    def __init__(self, rest_data) -> None: ...
    @property
    def name(self): ...
    @property
    def provider_kind(self): ...
    @property
    def target_name(self): ...
    @property
    def remaining_space(self): ...
    @property
    def volumes(self): ...

class BackupInfoStorPoolVolume(RESTMessageResponse):
    def __init__(self, rest_data) -> None: ...
    @property
    def name(self): ...
    @property
    def layer_type(self): ...
    @property
    def dl_size(self): ...
    @property
    def alloc_size(self): ...
    @property
    def usable_size(self): ...

class BackupQueues(RESTMessageResponse):
    def __init__(self, rest_data) -> None: ...
    @property
    def node_queues(self): ...
    @property
    def snap_queues(self): ...

class NodeQueue(RESTMessageResponse):
    def __init__(self, rest_data) -> None: ...
    @property
    def node_name(self): ...
    @property
    def queue(self): ...

class SnapQueue(RESTMessageResponse):
    def __init__(self, rest_data) -> None: ...
    @property
    def resource_name(self): ...
    @property
    def snapshot_name(self): ...
    @property
    def remote_name(self): ...
    @property
    def incremental(self): ...
    @property
    def based_on(self): ...
    @property
    def start_timestamp(self): ...
    @property
    def pref_node(self): ...
    @property
    def queue(self): ...

class ExternalFile(RESTMessageResponse):
    def __init__(self, rest_data) -> None: ...
    @property
    def path(self): ...
    @property
    def content(self): ...

class FileResponse(RESTMessageResponse):
    def __init__(self, rest_data) -> None: ...
    @property
    def files(self): ...

class Schedule(RESTMessageResponse):
    def __int__(self, rest_data) -> int: ...
    @property
    def schedule_name(self): ...
    @property
    def full_cron(self): ...
    @property
    def inc_cron(self): ...
    @property
    def keep_local(self): ...
    @property
    def keep_remote(self): ...
    @property
    def on_failure(self): ...
    @property
    def max_retries(self): ...

class ScheduleListResponse(RESTMessageResponse):
    def __init__(self, rest_data) -> None: ...
    @property
    def schedules(self): ...

class ScheduleResource(RESTMessageResponse):
    def __int__(self, rest_data) -> int: ...
    @property
    def resource_name(self): ...
    @property
    def remote_name(self): ...
    @property
    def schedule_name(self): ...
    @property
    def reason(self): ...
    @property
    def last_snap_time(self): ...
    @property
    def last_snap_inc(self): ...
    @property
    def next_exec_time(self): ...
    @property
    def next_exec_inc(self): ...
    @property
    def next_planned_full(self): ...
    @property
    def next_planned_inc(self): ...

class ScheduleResourceListResponse(RESTMessageResponse):
    def __init__(self, rest_data) -> None: ...
    @property
    def schedule_resources(self): ...

class ScheduleResourceDetails(RESTMessageResponse):
    def __int__(self, rest_data) -> int: ...
    @property
    def remote_name(self): ...
    @property
    def schedule_name(self): ...
    @property
    def controller(self): ...
    @property
    def resource_definition(self): ...
    @property
    def resource_group(self): ...

class ScheduleResourceDetailsListResponse(RESTMessageResponse):
    def __init__(self, rest_data) -> None: ...
    @property
    def schedule_resources(self): ...

class QuerySizeInfoSpawnResult(RESTMessageResponse):
    def __init__(self, rest_data) -> None: ...
    @property
    def node_name(self): ...
    @property
    def stor_pool_name(self): ...
    @property
    def stor_pool_oversubscription_ratio(self): ...

class QuerySizeInfoResponseSpaceInfo(RESTMessageResponse):
    def __init__(self, rest_data) -> None: ...
    @property
    def max_vlm_size_in_kib(self): ...
    @property
    def available_size_in_kib(self): ...
    @property
    def capacity_in_kib(self): ...
    @property
    def default_max_oversubscription_ratio(self): ...
    @property
    def next_spawn_result(self): ...

class QuerySizeInfoResponse(RESTMessageResponse):
    def __init__(self, rest_data) -> None: ...
    @property
    def space_info(self): ...
    @property
    def reports(self): ...

class EffectiveProp(RESTMessageResponse):
    def __init__(self, rest_data) -> None: ...
    @property
    def type(self): ...
    @property
    def value(self): ...
    @property
    def descr(self): ...
    @property
    def other(self): ...
