name: Setup Python env
description: Setup Python and dependencies
inputs:
  python-version:
    description: Python version to use
    required: true
runs:
  using: composite
  steps:
    - name: Set up uv
      uses: astral-sh/setup-uv@v7
      with:
        enable-cache: true
        cache-dependency-glob: uv.lock
        version: "0.10.11"

    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install dependencies
      shell: bash
      run: uv sync --all-extras --dev
