name: Setup Python env
description: Setup Python and pip
runs:
  using: "composite"
  steps:
    - name: Setup Python
      uses: actions/setup-python@v6
      with:
        python-version: "3.14"
        cache: "pip"

    - name: Install dependencies
      shell: bash
      run: pip install --upgrade pip
