from _typeshed import Incomplete

LOG_LEVEL: Incomplete
LOG_SYSLOG_FACILITY: Incomplete
LOG_TO_STDERR: bool

def configure_logging(): ...
def debug(message, *args, **kwargs): ...
def info(message, *args, **kwargs): ...
def warning(message, *args, **kwargs): ...
def error(message, *args, **kwargs): ...
def critical(message, *args, **kwargs): ...
def log_call_argv(): ...
def handle_unhandled_exceptions(exception_type, exception_value, exception_traceback): ...

_LOGGER: Incomplete
