from xapi import *
from _typeshed import Incomplete

get_str = str
long = int
unicode = str
str = bytes

class Datapath_server_dispatcher:
    _impl: Incomplete
    _dispatcher_dict: Incomplete
    def __init__(self, impl): ...
    def open(self, args): ...
    def attach(self, args): ...
    def activate(self, args): ...
    def activate_readonly(self, args): ...
    def import_activate(self, args): ...
    def deactivate(self, args): ...
    def detach(self, args): ...
    def close(self, args): ...
    def _dispatch(self, method, params): ...

class Datapath_skeleton:
    def __init__(self): ...
    def open(self, dbg, uri, persistent): ...
    def attach(self, dbg, uri, domain): ...
    def activate(self, dbg, uri, domain): ...
    def activate_readonly(self, dbg, uri, domain): ...
    def import_activate(self, dbg, uri, domain): ...
    def deactivate(self, dbg, uri, domain): ...
    def detach(self, dbg, uri, domain): ...
    def close(self, dbg, uri): ...

class Datapath_test:
    def __init__(self): ...
    def open(self, dbg, uri, persistent): ...
    def attach(self, dbg, uri, domain): ...
    def activate(self, dbg, uri, domain): ...
    def activate_readonly(self, dbg, uri, domain): ...
    def import_activate(self, dbg, uri, domain): ...
    def deactivate(self, dbg, uri, domain): ...
    def detach(self, dbg, uri, domain): ...
    def close(self, dbg, uri): ...

class Datapath_commandline:
    impl: Incomplete
    dispatcher: Incomplete
    def __init__(self, impl): ...
    def _parse_open(self): ...
    def _parse_attach(self): ...
    def _parse_activate(self): ...
    def _parse_activate_readonly(self): ...
    def _parse_import_activate(self): ...
    def _parse_deactivate(self): ...
    def _parse_detach(self): ...
    def _parse_close(self): ...
    def open(self): ...
    def attach(self): ...
    def activate(self): ...
    def activate_readonly(self): ...
    def import_activate(self): ...
    def deactivate(self): ...
    def detach(self): ...
    def close(self): ...

class Data_server_dispatcher:
    _impl: Incomplete
    _dispatcher_dict: Incomplete
    def __init__(self, impl): ...
    def copy(self, args): ...
    def mirror(self, args): ...
    def stat(self, args): ...
    def cancel(self, args): ...
    def destroy(self, args): ...
    def ls(self, args): ...
    def _dispatch(self, method, params): ...

class Data_skeleton:
    def __init__(self): ...
    def copy(self, dbg, uri, domain, remote, blocklist): ...
    def mirror(self, dbg, uri, domain, remote): ...
    def stat(self, dbg, operation): ...
    def cancel(self, dbg, operation): ...
    def destroy(self, dbg, operation): ...
    def ls(self, dbg): ...

class Data_test:
    def __init__(self): ...
    def copy(self, dbg, uri, domain, remote, blocklist): ...
    def mirror(self, dbg, uri, domain, remote): ...
    def stat(self, dbg, operation): ...
    def cancel(self, dbg, operation): ...
    def destroy(self, dbg, operation): ...
    def ls(self, dbg): ...

class Data_commandline:
    impl: Incomplete
    dispatcher: Incomplete
    def __init__(self, impl): ...
    def _parse_copy(self): ...
    def _parse_mirror(self): ...
    def _parse_stat(self): ...
    def _parse_cancel(self): ...
    def _parse_destroy(self): ...
    def _parse_ls(self): ...
    def copy(self): ...
    def mirror(self): ...
    def stat(self): ...
    def cancel(self): ...
    def destroy(self): ...
    def ls(self): ...

class datapath_server_dispatcher:
    Datapath: Incomplete
    Data: Incomplete
    _dispatcher_dict: Incomplete
    def __init__(self, Datapath=None, Data=None): ...
    def _dispatch(self, method, params): ...

class datapath_server_test(datapath_server_dispatcher):
    def __init__(self): ...
