from xapi import *
from _typeshed import Incomplete

get_str = str
long = int
unicode = str
str = bytes

class Plugin_server_dispatcher:
    _impl: Incomplete
    _dispatcher_dict: Incomplete
    def __init__(self, impl): ...
    def query(self, args): ...
    def ls(self, args): ...
    def diagnostics(self, args): ...
    def _dispatch(self, method, params): ...

class Plugin_skeleton:
    def __init__(self): ...
    def query(self, dbg): ...
    def ls(self, dbg): ...
    def diagnostics(self, dbg): ...

class Plugin_test:
    def __init__(self): ...
    def query(self, dbg): ...
    def ls(self, dbg): ...
    def diagnostics(self, dbg): ...

class Plugin_commandline:
    impl: Incomplete
    dispatcher: Incomplete
    def __init__(self, impl): ...
    def _parse_query(self): ...
    def _parse_ls(self): ...
    def _parse_diagnostics(self): ...
    def query(self): ...
    def ls(self): ...
    def diagnostics(self): ...

class plugin_server_dispatcher:
    Plugin: Incomplete
    _dispatcher_dict: Incomplete
    def __init__(self, Plugin=None): ...
    def _dispatch(self, method, params): ...

class plugin_server_test(plugin_server_dispatcher):
    def __init__(self): ...
