from xapi import *
from _typeshed import Incomplete

get_str = str
long = int
unicode = str
str = bytes

class Task_server_dispatcher:
    _impl: Incomplete
    _dispatcher_dict: Incomplete
    def __init__(self, impl): ...
    def stat(self, args): ...
    def cancel(self, args): ...
    def destroy(self, args): ...
    def ls(self, args): ...
    def _dispatch(self, method, params): ...

class Task_skeleton:
    def __init__(self): ...
    def stat(self, dbg, id): ...
    def cancel(self, dbg, id): ...
    def destroy(self, dbg, id): ...
    def ls(self, dbg): ...

class Task_test:
    def __init__(self): ...
    def stat(self, dbg, id): ...
    def cancel(self, dbg, id): ...
    def destroy(self, dbg, id): ...
    def ls(self, dbg): ...

class Task_commandline:
    impl: Incomplete
    dispatcher: Incomplete
    def __init__(self, impl): ...
    def _parse_stat(self): ...
    def _parse_cancel(self): ...
    def _parse_destroy(self): ...
    def _parse_ls(self): ...
    def stat(self): ...
    def cancel(self): ...
    def destroy(self): ...
    def ls(self): ...

class task_server_dispatcher:
    Task: Incomplete
    _dispatcher_dict: Incomplete
    def __init__(self, Task=None): ...
    def _dispatch(self, method, params): ...

class task_server_test(task_server_dispatcher):
    def __init__(self): ...
