from xapi import *
from _typeshed import Incomplete

get_str = str
long = int
unicode = str
str = bytes

class Sr_not_attached(Rpc_light_failure):
    arg_0: Incomplete
    def __init__(self, arg_0): ...

class SR_does_not_exist(Rpc_light_failure):
    arg_0: Incomplete
    def __init__(self, arg_0): ...

class Volume_does_not_exist(Rpc_light_failure):
    arg_0: Incomplete
    def __init__(self, arg_0): ...

class Cancelled(Rpc_light_failure):
    arg_0: Incomplete
    def __init__(self, arg_0): ...

class Activated_on_another_host(Rpc_light_failure):
    arg_0: Incomplete
    def __init__(self, arg_0): ...

class SR_server_dispatcher:
    _impl: Incomplete
    _dispatcher_dict: Incomplete
    def __init__(self, impl): ...
    def probe(self, args): ...
    def create(self, args): ...
    def attach(self, args): ...
    def detach(self, args): ...
    def destroy(self, args): ...
    def stat(self, args): ...
    def set_name(self, args): ...
    def set_description(self, args): ...
    def ls(self, args): ...
    def _dispatch(self, method, params): ...

class SR_skeleton:
    def __init__(self): ...
    def probe(self, dbg, configuration): ...
    def create(self, dbg, uuid, configuration, name, description): ...
    def attach(self, dbg, configuration): ...
    def detach(self, dbg, sr): ...
    def destroy(self, dbg, sr): ...
    def stat(self, dbg, sr): ...
    def set_name(self, dbg, sr, new_name): ...
    def set_description(self, dbg, sr, new_description): ...
    def ls(self, dbg, sr): ...

class SR_test:
    def __init__(self): ...
    def probe(self, dbg, configuration): ...
    def create(self, dbg, uuid, configuration, name, description): ...
    def attach(self, dbg, configuration): ...
    def detach(self, dbg, sr): ...
    def destroy(self, dbg, sr): ...
    def stat(self, dbg, sr): ...
    def set_name(self, dbg, sr, new_name): ...
    def set_description(self, dbg, sr, new_description): ...
    def ls(self, dbg, sr): ...

class SR_commandline:
    impl: Incomplete
    dispatcher: Incomplete
    def __init__(self, impl): ...
    def _parse_probe(self): ...
    def _parse_create(self): ...
    def _parse_attach(self): ...
    def _parse_detach(self): ...
    def _parse_destroy(self): ...
    def _parse_stat(self): ...
    def _parse_set_name(self): ...
    def _parse_set_description(self): ...
    def _parse_ls(self): ...
    def probe(self): ...
    def create(self): ...
    def attach(self): ...
    def detach(self): ...
    def destroy(self): ...
    def stat(self): ...
    def set_name(self): ...
    def set_description(self): ...
    def ls(self): ...

class Volume_server_dispatcher:
    _impl: Incomplete
    _dispatcher_dict: Incomplete
    def __init__(self, impl): ...
    def create(self, args): ...
    def snapshot(self, args): ...
    def clone(self, args): ...
    def copy(self, args): ...
    def destroy(self, args): ...
    def revert(self, args): ...
    def set_name(self, args): ...
    def set_description(self, args): ...
    def set(self, args): ...
    def unset(self, args): ...
    def resize(self, args): ...
    def stat(self, args): ...
    def compare(self, args): ...
    def similar_content(self, args): ...
    def enable_cbt(self, args): ...
    def disable_cbt(self, args): ...
    def data_destroy(self, args): ...
    def list_changed_blocks(self, args): ...
    def compose(self, args): ...
    def _dispatch(self, method, params): ...

class Volume_skeleton:
    def __init__(self): ...
    def create(self, dbg, sr, name, description, size, sharable): ...
    def snapshot(self, dbg, sr, key): ...
    def clone(self, dbg, sr, key): ...
    def copy(self, dbg, sr, key, dest_sr): ...
    def destroy(self, dbg, sr, key): ...
    def revert(self, dbg, sr, snapshot, key): ...
    def set_name(self, dbg, sr, key, new_name): ...
    def set_description(self, dbg, sr, key, new_description): ...
    def set(self, dbg, sr, key, k, v): ...
    def unset(self, dbg, sr, key, k): ...
    def resize(self, dbg, sr, key, new_size): ...
    def stat(self, dbg, sr, key): ...
    def compare(self, dbg, sr, key, key2): ...
    def similar_content(self, dbg, sr, key): ...
    def enable_cbt(self, dbg, sr, key): ...
    def disable_cbt(self, dbg, sr, key): ...
    def data_destroy(self, dbg, sr, key): ...
    def list_changed_blocks(self, dbg, sr, key, key2, offset, length): ...
    def compose(self, dbg, sr, key, key2): ...

class Volume_test:
    def __init__(self): ...
    def create(self, dbg, sr, name, description, size, sharable): ...
    def snapshot(self, dbg, sr, key): ...
    def clone(self, dbg, sr, key): ...
    def copy(self, dbg, sr, key, dest_sr): ...
    def destroy(self, dbg, sr, key): ...
    def revert(self, dbg, sr, snapshot, key): ...
    def set_name(self, dbg, sr, key, new_name): ...
    def set_description(self, dbg, sr, key, new_description): ...
    def set(self, dbg, sr, key, k, v): ...
    def unset(self, dbg, sr, key, k): ...
    def resize(self, dbg, sr, key, new_size): ...
    def stat(self, dbg, sr, key): ...
    def compare(self, dbg, sr, key, key2): ...
    def similar_content(self, dbg, sr, key): ...
    def enable_cbt(self, dbg, sr, key): ...
    def disable_cbt(self, dbg, sr, key): ...
    def data_destroy(self, dbg, sr, key): ...
    def list_changed_blocks(self, dbg, sr, key, key2, offset, length): ...
    def compose(self, dbg, sr, key, key2): ...

class Volume_commandline:
    impl: Incomplete
    dispatcher: Incomplete
    def __init__(self, impl): ...
    def _parse_create(self): ...
    def _parse_snapshot(self): ...
    def _parse_clone(self): ...
    def _parse_copy(self): ...
    def _parse_destroy(self): ...
    def _parse_revert(self): ...
    def _parse_set_name(self): ...
    def _parse_set_description(self): ...
    def _parse_set(self): ...
    def _parse_unset(self): ...
    def _parse_resize(self): ...
    def _parse_stat(self): ...
    def _parse_compare(self): ...
    def _parse_similar_content(self): ...
    def _parse_enable_cbt(self): ...
    def _parse_disable_cbt(self): ...
    def _parse_data_destroy(self): ...
    def _parse_list_changed_blocks(self): ...
    def _parse_compose(self): ...
    def create(self): ...
    def snapshot(self): ...
    def clone(self): ...
    def copy(self): ...
    def destroy(self): ...
    def revert(self): ...
    def set_name(self): ...
    def set_description(self): ...
    def set(self): ...
    def unset(self): ...
    def resize(self): ...
    def stat(self): ...
    def compare(self): ...
    def similar_content(self): ...
    def enable_cbt(self): ...
    def disable_cbt(self): ...
    def data_destroy(self): ...
    def list_changed_blocks(self): ...
    def compose(self): ...

class volume_server_dispatcher:
    SR: Incomplete
    Volume: Incomplete
    _dispatcher_dict: Incomplete
    def __init__(self, SR=None, Volume=None): ...
    def _dispatch(self, method, params): ...

class volume_server_test(volume_server_dispatcher):
    def __init__(self): ...
